Gallery/urls.py
# from django.contrib import admin
import picha
from django.contrib import admin
from django.urls import path,include
# from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('picha.urls',namespace='picha'))
] 

picha/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='Gallery'
urlpatterns=[
    path('', views.homepage, name='landing'), 
    path('gallery/', views.gallery, name='gallery'),
    path('search/', views.search, name='search'),
    path('location/<str:city>', views.search, name='search')

]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

picha/models.py
from django.db import models

# Create your models here.
#category model
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name 

    def save_category(self):
        self.save()
    
    def delete_category(self):
        self.delete()

    @classmethod
    def update_category(cls, search_term , new_cat):
        try:
            to_update = Category.objects.get(name = search_term)
            to_update.name = new_cat
            to_update.save()
            return to_update
        except Category.DoesNotExist:
            print('Category you specified does not exist')

#image model
class Images(models.Model):
    image_link = models.ImageField(upload_to='images/')
    title = models.CharField(max_length=80)
    description = models.TextField()
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    location = models.ForeignKey('Locations', on_delete=models.CASCADE, default=1)

    # add image categories model
    def __str__(self):
        return self.title

    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    @classmethod
    def update_image(self, new_url):
        try:
            self.image_link = new_url
            self.save()
            return self
        except self.DoesNotExist:
            print('Image you specified does not exist')    
    

    @classmethod
    def get_all(cls):
        pics = Images.objects.all()
        return pics
    
    
    @classmethod
    def get_image_by_id(cls, id):
        retrieved = Images.objects.get(id = id)
        return retrieved

    @classmethod
    def search_image(cls, cat):
        retrieved = cls.objects.filter(category__name__icontains=cat) 
        return retrieved #list of instances

    @classmethod
    def filter_by_location(cls ,location):
        retrieved = Images.objects.filter(location__city__icontains=location)
        return retrieved

#locations model
class Locations(models.Model):
    city = models.CharField(max_length=30)
    country = models.CharField(max_length=30)

    def __str__(self):
        return self.city

    def save_location(self):
        self.save()    

    def delete_location(self):
        self.delete()

    @classmethod
    def update_location(cls, search_term , new_locale):
        try:
            to_update = Locations.objects.get(country = search_term)
            to_update.city = new_locale
            to_update.save()
            return to_update
        except Locations.DoesNotExist:
            print('Location you specified does not exist') 
     

picha/views.py
from django.shortcuts import render
from .models import Images, Locations

# Create your views here.
def homepage(request):
    return render(request, 'index.html')

def gallery(request):
    locations =Locations.objects.all()
    if 'category' in request.GET and request.GET['category']:
        search_term = request.GET.get('category')
        pictures = Images.search_image(search_term)
        return render(request, 'gallery.html', {'pictures': pictures,'locations':locations})
    else:
        pictures = Images.get_all()
        return render(request, 'gallery.html', {'pictures': pictures,'locations':locations})

def search(request,city):
    locations =Locations.objects.all()

    pictures = Images.filter_by_location(city)
    return render(request, 'gallery.html', {'pictures': pictures,'locations':locations})

picha/templates/base.html
{% load bootstrap4%}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title> Gallery </title>
    {% endif %}

    <!--  -->
    {% block styles %} {% bootstrap_css %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>

<body>
    
    <!--  -->
    {% block content %}{{block.super}} {% endblock %}

    {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript %}
    {% endblock %}
</body>

</html> 

picha/templates/gallery.html
{% extends 'base.html' %}
{% include 'category.html' %}

<!--  -->
{% block content %} {{block.super}}
<div class="category-nav">
    <div class="category">
      <a href="#">Nature</a>
    </div>
    <div class="category">
      <a href="#">Architecture</a>
    </div>
    <div class="category">
      <a href="#">Fashion</a>
    </div>
    <div class="category">
      <a href="#">Street photography</a>
    </div>
  </div>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg ">
        <div class="col-sm-4 col-md-4 navbar-left">
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-filter"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% for item in locations %}
                    <a class="dropdown-item" href="/location/{{item.city}} ">{{item.city}} </a> {% endfor %}
                </div>
            </div>
        </div>
    </nav>
</div>

<div class="search-form">
    <form action="{% url 'picha:gallery' %}" method="GET">
      <input type="text" placeholder="Search category" name="category">
    </form>
</div>

<div class="block">
    <div class="row">
        
        <div class="gallery">
            {% for item in pictures %}
            <div class="gallery-item" data-toggle="modal" data-target="#{{item.id}}">
                <img src="{{item.image_link.url}}" alt="" class="gallery-image">
                <div class="gallery-item-info">
                    <ul>
                        <li class="gallery-item-likes"><span class="visually-hidden"></span> {{item.category}} </li>
                    </ul>
                </div>
            </div>
            <div class="modal fade " id="{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-md" role="document">
                    <div class="modal-content popup">
                        <div class="modal-header">
                            <button type="button" data-dismiss="modal">Close
                        </div>
                        <div class="modal-body text-center">
                            <h4 class="modal-title" id="imageheader">{{item.title}}</h4>
                            <img src="{{item.image_link.url}}" alt="{{item.name}}" class="img-responsive" width="300" height="300">
                            <p class="text-center">{{item.description}}</p>
                            <ul class="list-inline list-unstyled">
                                <li class="list-inline-item gallery-item-likes"><span class="visually-hidden"></span> {{item.category}} </li>
                                <li class="list-inline-item gallery-item-comments"><span class="visually-hidden"></span> {{item.location}} </li>
                            </ul>
                        </div>
                        <div class="modal-footer">
                            <input type="text" value="{{request.scheme}}://{{request.get_host}}{{item.image_link.url}}" id="myInput">
                            <button onclick="myFunction()" onmouseout="outFunc()" data-toggle="tooltip" title="copied!">Copy text</button>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %} {% block scripts %} {{block.super}}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %} -->

picha/templates/index.html
{% load bootstrap4 %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Gallery </title>

    <!--  -->
    {% block styles %} {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenMax.min.js"></script>
    
    {% endblock %}
</head>

<body>
  
  {% include 'navbar.html' %}

    <div class="wrapper">
        <div class="left"></div>
        <div class="right"></div>

        <div class="content">
          <div class="img-wrapper">
            <div class="karina">
              <img src="{% static 'img/landing.jpeg'%}" class="img-responsive" alt="Image">
            </div>
          </div>
    
          <div class="info">
            <ul>
              <li>Gallery.com</li>
              <li>@gallery.Ke</li>
              <li>Gallery.com</li>
              <li><i class="fa fa-share-alt"></i></li>
            </ul>
          </div>
    
          <div class="text">
            <h1>Gallery Kenya</h1>
            <p>Art.Creativity</p>
          </div>
    
          <!-- <div class="name">karina tes</div> -->
    
          <div class="bottomnav">
            <ul>
              <li>Artists</li>
              <li>Images</li>
              <li>contact</li>
            </ul>
          </div>
        </div>
      </div>
      
    

    <!--  -->
    {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>

      TweenMax.to('.left', 2, {
        delay: .8,
        width: '50%',
        ease: Power2.easeInOut
      })
  
      TweenMax.to('.right', 2, {
        delay: .6,
        width: '50%',
        ease: Power3.easeInOut
      })
  
      TweenMax.from('.nav', 2, {
        delay: .8,
        opacity: 0,
        ease: Expo.easeInOut
      })
  
      TweenMax.from('.text h1', 2, {
        delay: .6,
        x: 1000,
        ease: Circ.easeInOut
      })
  
      TweenMax.from('.text p', 2, {
        delay: .7,
        x: 1000,
        ease: Circ.easeInOut
      })
  
      TweenMax.to('.karina', 2, {
        delay: 1.5,
        width: '1000px',
        ease: Power2.easeInOut
      })
  
      TweenMax.staggerFrom('.bottomnav ul li', 2, {
        delay: 1,
        x: 1000,
        ease: Circ.easeInOut
      }, 0.08)
  
      TweenMax.from('.info', 2, {
        delay: 1.5,
        y: 100,
        ease: Circ.easeInOut
      })
  
      TweenMax.from('.name', 2, {
        delay: 1.5,
        x: -600,
        ease: Circ.easeInOut
      })
     </script>
    {% bootstrap_javascript %}
     {% endblock %}
</body>

</html> 

picha/templates/navbar.html
<nav class="nav">
    <ul>
      <li class><a href=" {% url 'picha:gallery' %}">Gallery</a></li>
      <li class><a href=" {% url 'picha:gallery' %}">Explore</a></li>
    </ul>
  </nav>

picha/templates/search.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <div class="row">
        {% if results %}
        <h2> Found {{results|length }} of term '{{message}}' </h2>
        {% else %}
        <h2> Found 0 results in '{{message}}' </h2>
        {% endif %}
    </div>

    <div class="row">
        {% if results %} {% for item in results %}
        <div class="col-sm-6 col-md-3">
            <h2>{{item.title}}</h2>
        </div>
        {% endfor %} {% endif %}
    </div>
</div>
{% endblock %} 